### ISSUE TITLE
Hardcoded interface name?

### ISSUE THREAD

**Issue by munikarmanish** [karkipy/whichIp#1]
https://github.com/karkipy/whichIp/blob/ea93050dde4c78f5d8fc502dd3063c4129b61c7c/whichIp#L2

When I run this in my Ubuntu, I get this:
```
manish@ubuntu:~$ ifconfig en0
en0: error fetching interface information: Device not found
```

Maybe you can parse the output of `ip link` to get the appropriate interface name.
```
manish@ubuntu:~$ ip link
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: enp0s3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP mode DEFAULT group default qlen 1000
    link/ether 08:00:27:9e:a3:46 brd ff:ff:ff:ff:ff:ff
```

**Comment by karkipy** [comment]
hey @munikarmanish  I had not considered it for other device, I will update it shortly

**Comment by karkipy** [comment]
@munikarmanish  , I have addressed the problem do check and let me know
